jobs:
  sample_operators_tests:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Minikube-Kubernetes
      uses: manusa/actions-setup-minikube@v2.10.0
      with:
        driver: docker
        github token: ${{ secrets.GITHUB_TOKEN }}
        kubernetes version: v1.29.1
        minikube version: v1.32.0
    - continue-on-error: true
      name: Set up Java and Maven
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Build SDK
      run: mvn install -DskipTests
    - continue-on-error: true
      name: Run integration tests in local mode
      run: 'mvn test -P end-to-end-tests

        '
      working-directory: ${{ matrix.sample_dir }}
    - continue-on-error: true
      name: Run E2E tests as a deployment
      run: 'eval $(minikube -p minikube docker-env)

        mvn jib:dockerBuild test -P end-to-end-tests -Dtest.deployment=remote

        '
      working-directory: ${{ matrix.sample_dir }}
    strategy:
      matrix:
        sample_dir:
        - sample-operators/mysql-schema
        - sample-operators/tomcat-operator
        - sample-operators/webpage
        - sample-operators/leader-election
name: Integration & End to End tests
on:
  repository_dispatch:
    types: trigger-ga___e2e-test.yml
