env:
  MAVEN_ARGS: -V -ntp -e -f ${{ inputs.project_dir }}/pom.xml
jobs:
  publish:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout "${{inputs.version_branch}}" branch
      uses: actions/checkout@v4
      with:
        ref: ${{inputs.version_branch}}
    - continue-on-error: true
      name: Set up Java and Maven
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      env:
        RELEASE_VERSION: ${{ github.event.release.tag_name }}
      name: Change version to release version
      run: 'mvn ${MAVEN_ARGS} versions:set -DnewVersion="${RELEASE_VERSION:1}" versions:commit
        -DprocessAllModules

        '
    - continue-on-error: true
      name: Release Maven package
      uses: samuelmeuli/action-maven-publish@v1
      with:
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        maven_args: ${{ env.MAVEN_ARGS }}
        maven_profiles: release
        nexus_password: ${{ secrets.OSSRH_TOKEN }}
        nexus_username: ${{ secrets.OSSRH_USERNAME }}
  update-working-version:
    if: '!contains(github.event.release.tag_name, ''RC'')'
    needs: publish
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout "${{inputs.version_branch}}" branch
      uses: actions/checkout@v4
      with:
        ref: ${{inputs.version_branch}}
    - continue-on-error: true
      name: Set up Java and Maven
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      env:
        RELEASE_VERSION: ${{ github.event.release.tag_name }}
      name: Update version to new SNAPSHOT version
      run: 'mvn ${MAVEN_ARGS} build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT
        versions:commit -DprocessAllModules

        git config --local user.email "action@github.com"

        git config --local user.name "GitHub Action"

        git commit -m "Set new SNAPSHOT version into pom files." -a

        '
    - continue-on-error: true
      name: Push changes to branch
      uses: ad-m/github-push-action@master
      with:
        branch: ${{inputs.version_branch}}
        github_token: ${{ secrets.GITHUB_TOKEN }}
name: Release project in specified directory
on:
  repository_dispatch:
    types: trigger-ga___release-project-in-dir.yml
