concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}-${{ github.workflow }}
env:
  MAVEN_ARGS: -V -ntp -e
jobs:
  test:
    if: ${{ ( github.event_name == 'push' ) || ( github.event_name == 'pull_request'
      && github.event.pull_request.head.repo.owner.login == 'java-operator-sdk' )
      }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up Java and Maven
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-sonar
        path: ~/.sonar/cache
        restore-keys: ${{ runner.os }}-sonar
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      name: Build and analyze
      run: mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent clean install verify
        org.jacoco:jacoco-maven-plugin:report org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        -Dsonar.projectKey=java-operator-sdk_java-operator-sdk
name: Sonar
on:
  repository_dispatch:
    types: trigger-ga___sonar.yml
